apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-premium
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 150Gi
