apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
